### ISSUE TITLE
Add Both Dark and White theme

### ISSUE THREAD

**Issue by abhisheknaiidu** [abhisheknaiidu/a-pop#16]
## 🚀 Feature

Right now, we just have dark theme in our web-app, but we can customise it by proving a toggle button to user, to switch between the themes.

**Comment by VaibhavAcharya** [comment]
I would like to pull this up for Hacktoberfest.

**Comment by VaibhavAcharya** [comment]
### Questions

- Where should the toggle button reside ?
- Should it have an option for system theme ?
- Should the theme preference persist in local storage ?

### Some stuff I would like to do

- Default font to this system font stack :
`[
            "system-ui",
            "-apple-system",
            "BlinkMacSystemFont",
            "Segoe UI",
            "Roboto",
            "Helvetica Neue",
            "Arial",
            "Noto Sans",
            "sans-serif",
            "Apple Color Emoji",
            "Segoe UI Emoji",
            "Segoe UI Symbol",
            "Noto Color Emoji"
]`

**Comment by abhisheknaiidu** [comment]
Sorry @VaibhavAcharya , But I think someone has already made a PR regarding this!
