### ISSUE TITLE
Play songs no matter where I click on them

### ISSUE THREAD

**Issue by Jighdan** [abhisheknaiidu/a-pop#8]
The buttons for `play` and `add to the playlist` are pretty small, so, maybe being able to play a song, even if you just click the picture would be a better experience

**Comment by abhisheknaiidu** [comment]
It sounds good tho, but don't know how it looks after implementing it, 
Are you interested in doing this?

**Comment by Jighdan** [comment]
Hey- I haven't done anything in React, but surely I'd like to give it a try. Give me a couple of days.

**Comment by abhisheknaiidu** [comment]
@Jighdan Sure!

**Comment by Jighdan** [comment]
Hey~ Apologies for not getting back sooner; been busy, won't be able to apply this feature.
